// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZTTphQtFugTe8f5J7G71s3PW1nvqM2Cs',
    appId: '1:1044763814126:android:b197405aa7e27fb4d26bff',
    messagingSenderId: '1044763814126',
    projectId: 'chat-efea1',
    storageBucket: 'chat-efea1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGLqW4YYzrCHHR9OIJKbWkRhqEdS2bGMU',
    appId: '1:1044763814126:ios:487d5efedca9022cd26bff',
    messagingSenderId: '1044763814126',
    projectId: 'chat-efea1',
    storageBucket: 'chat-efea1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBNb9dkrIAP3akLaYAUdQ3hUUBUvIx0uM',
    appId: '1:1044763814126:web:16182e8d557e8387d26bff',
    messagingSenderId: '1044763814126',
    projectId: 'chat-efea1',
    authDomain: 'chat-efea1.firebaseapp.com',
    storageBucket: 'chat-efea1.appspot.com',
    measurementId: 'G-RRD7R98QYH',
  );
}
